### ISSUE TITLE
UMD build

### ISSUE THREAD

**Issue by cedricdelpoux** [enuchi/gas-client#4]
Hi, 

it could be useful to have an UMD build to use with your [React-Google-Apps-Script](https://github.com/enuchi/React-Google-Apps-Script) and the [DynamicCdnWebpackPlugin](https://github.com/mastilver/dynamic-cdn-webpack-plugin).

What do you think?

**Comment by enuchi** [comment]
What did you have in mind?

**Comment by cedricdelpoux** [comment]
A dist folder with an UMD build to include **gas-client** as external dependency like you did for **react-bootstrap** [in your webpack config](https://github.com/enuchi/React-Google-Apps-Script/blob/master/webpack.config.js#L165-L171)

**Comment by enuchi** [comment]
Ah, you mean so gas-client can be loaded from a cdn?

**Comment by cedricdelpoux** [comment]
yes, it could be useful to reduce bundle size

**Comment by enuchi** [comment]
Hm, it probably only adds a couple lines of code when minified/in production, but in general agree it would be good to have the option. Let me think about best way to add and whether it makes sense to include webpack here.

**Comment by ramkumar2098** [comment]
any updates on this, @enuchi?

**Comment by enuchi** [comment]
Added to v1.1.0.
